### PR TITLE
Fix libxml2 warnings

### LINKED ISSUE #19: Deprecation and incompatible pointer type warning on new libxml2 versions
```
# github.com/terminalstatic/go-xsd-validate
./libxml2.go: In function ‘cleanup’:
./libxml2.go:116:5: warning: ‘xmlSchemaCleanupTypes’ is deprecated [-Wdeprecated-declarations]
  116 |     xmlSchemaCleanupTypes();
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from ./libxml2.go:9:
/usr/include/libxml2/libxml/xmlschemastypes.h:37:17: note: declared here
   37 |                 xmlSchemaCleanupTypes           (void);
      |                 ^~~~~~~~~~~~~~~~~~~~~
./libxml2.go: In function ‘parseSchema’:
./libxml2.go:186:5: warning: ‘xmlLineNumbersDefault’ is deprecated [-Wdeprecated-declarations]
  186 |     xmlLineNumbersDefault(1);
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libxml2/libxml/tree.h:17,
                 from /usr/include/libxml2/libxml/schemasInternals.h:24,
                 from /usr/include/libxml2/libxml/xmlschemastypes.h:19:
/usr/include/libxml2/libxml/parser.h:967:17: note: declared here
  967 |                 xmlLineNumbersDefault   (int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~
./libxml2.go: In function ‘cParseDoc’:
./libxml2.go:247:5: warning: ‘xmlLineNumbersDefault’ is deprecated [-Wdeprecated-declarations]
  247 |     xmlLineNumbersDefault(1);
      |     ^~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:967:17: note: declared here
  967 |                 xmlLineNumbersDefault   (int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~
./libxml2.go: In function ‘cValidate’:
./libxml2.go:300:5: warning: ‘xmlLineNumbersDefault’ is deprecated [-Wdeprecated-declarations]
  300 |     xmlLineNumbersDefault(1);
      |     ^~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:967:17: note: declared here
  967 |                 xmlLineNumbersDefault   (int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~
./libxml2.go:328:59: warning: passing argument 2 of ‘xmlSchemaSetValidStructuredErrors’ from incompatible pointer type [-Wincompatible-pointer-types]
  328 |             xmlSchemaSetValidStructuredErrors(schemaCtxt, simpleStructErrorCallback,
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/xmlschemastypes.h:20:
/usr/include/libxml2/libxml/xmlschemas.h:185:65: note: expected ‘xmlStructuredErrorFunc’ {aka ‘void (*)(void *, const struct _xmlError *)’} but argument is of type ‘void (*)(void *, xmlError *)’ {aka ‘void (*)(void *, struct _xmlError *)’}
  185 |                                          xmlStructuredErrorFunc serror,
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
./libxml2.go: In function ‘cValidateBuf’:
./libxml2.go:353:5: warning: ‘xmlLineNumbersDefault’ is deprecated [-Wdeprecated-declarations]
  353 |     xmlLineNumbersDefault(1);
      |     ^~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:967:17: note: declared here
  967 |                 xmlLineNumbersDefault   (int val);
      |                 ^~~~~~~~~~~~~~~~~~~~~
```

These changes seem to appear in 2.12.0.

I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by WGH-**
Every commit has detailed description.

I've tested this on Docker images `golang:1.22-bullseye` (libxml2 2.9.10), `golang:1.22-bookworm` (libxml2 2.9.14), and on my own system (libxml2 2.12.6).

Closes #19

### CODE REVIEW

**Comment by terminalstatic** [comment]
Thanks for the commits and your detailed comments. I haven't tested them, but your comments seemed reasonable.
I'd really like to incorparate changes of a fork into the code and tag a new version in the near future, at least then I'll test it.

**Comment by WGH-** [comment]
> Thanks for the commits and your detailed comments. I haven't tested them, but your comments seemed reasonable.

What if I'm just an LLM? :)

(just kidding, no, I'm not)

**Comment by terminalstatic** [comment]
Well that's why I didn't tag it with a version yet for I'm quite paranoid of getting spoofed by a LLM ;).
And I guess claiming that you are no LLM is probably exactly what a LLM would do ... 
Actually I just had such an experience yesterday, no kidding.

**Comment by nickgrim** [comment]
Sorry to be That Guy, but: any updates on when a new release with this might be tagged?

**Comment by terminalstatic** [comment]
I

> Sorry to be That Guy, but: any updates on when a new release with this might be tagged?

If somebody else except the author of the pull request can reliably confirm that everything works as expected I'll probably tag it (given how amazingly well the pull request was documented I'd actually be pretty surprised if it won't work, but hey, never trust a possible llm hinting to be a llm hinting to be human;)) . And I'd be even less hesitant to do so if that somebody also puts the c code through valgrind just to make sure. There were actually memory leaks in the libxml2 library in the past. As I don't need this for myself at the moment and as I'm coding in a complete different realm lately I admit I have not much motivation to do this myself currently. Did you happen to try it out the master branch?

**Comment by nickgrim** [comment]
> Did you happen to try it out the master branch?

I didn't try `master`, but I added a `replace` using the fork to my `go.mod`:
```
$ tail -n3 go.mod
// go-xsd-validate v0.1.5 doesn't work with libxml2 > v2.12, so replace it with patched version.
// Thie can be removed after https://github.com/terminalstatic/go-xsd-validate/pull/20 is merged (and released).
replace github.com/terminalstatic/go-xsd-validate v0.1.5 => github.com/WGH-/go-xsd-validate v0.0.0-20240530182831-6395660640fb
```
…and this fixes the ~test~ build failures I was seeing, and has been running happily in production for about a month.

**Comment by terminalstatic** [comment]
> …and this fixes the ~test~ build failures I was seeing, and has been running happily in production for about a month.

Like having it running in a long running service with enough validations to have noticed sth. like memory leaks by now?

**Comment by nickgrim** [comment]
> Like having it running in a long running service …

Mmm, not really. We're using this in a test to validate some payloads, but it's not a part of a long-running binary.

> …with enough validations to have noticed sth. like memory leaks by now?

Just to check: you're interested in memory leaks _in the code of this MR_, right? It feels like "leaks from `libxml2`" would be out-of-scope for _this_, wouldn't they?

**Comment by WGH-** [comment]
Well, I suppose at the very least we could run the test suite with some absurd `-count`, and observe RSS externally?

```
go test -tags apitest ./ -count 1000000 -timeout 1h -skip TestValidateWithXsdHandlerHttpPass
```

I skipped `TestValidateWithXsdHandlerHttpPass` because it downloads a lot of schema files, and that takes a lot of time.

The run took 18m20s, RSS was stable at around 20 mebibytes.

**Comment by WGH-** [comment]
@nickgrim 

> go-xsd-validate v0.1.5 doesn't work with libxml2 > v2.12, so replace it with patched version.

I was sure it does work, it just outputs a lot of annoying warnings on compilation,

**Comment by nickgrim** [comment]
I really do get **errors** on compilation. With this `xsdtest.go`:
```
package main

import (
        "fmt"

        xsdvalidate "github.com/terminalstatic/go-xsd-validate"
)

func main() {
        err := xsdvalidate.Init()
        fmt.Println("ok")
}
```
I get:
```
$ go build xsdtest.go || echo $?
# github.com/terminalstatic/go-xsd-validate
../../../go/pkg/mod/github.com/terminalstatic/go-xsd-validate@v0.1.5/libxml2.go: In function 'cValidate':
../../../go/pkg/mod/github.com/terminalstatic/go-xsd-validate@v0.1.5/libxml2.go:328:59: error: passing argument 2 of 'xmlSchemaSetValidStructuredErrors' from incompatible pointer type [-Wincompatible-pointer-types]
  328 |             xmlSchemaSetValidStructuredErrors(schemaCtxt, simpleStructErrorCallback,
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           void (*)(void *, xmlError *) {aka void (*)(void *, struct _xmlError *)}
In file included from /usr/include/libxml2/libxml/xmlschemastypes.h:20,
                 from ../../../go/pkg/mod/github.com/terminalstatic/go-xsd-validate@v0.1.5/libxml2.go:9:
/usr/include/libxml2/libxml/xmlschemas.h:185:65: note: expected 'xmlStructuredErrorFunc' {aka 'void (*)(void *, const struct _xmlError *)'} but argument is of type 'void (*)(void *, xmlError *)' {aka 'void (*)(void *, struct _xmlError *)'}
  185 |                                          xmlStructuredErrorFunc serror,
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
1
```
```
$ pacman -Ss ^libxml2$
core/libxml2 2.13.3-1 [installed]
    XML C parser and toolkit
```

**Comment by WGH-** [comment]
I see, Arch Linux gcc defaults are likely more strict than mine on Gentoo.

**Comment by jcleira** [comment]
Would it be possible to kindly generate a tag after this has been merged? Just as an update, we are currently relying on an untagged version of the library. Thank you!

**Comment by WGH-** [comment]
What if @jcleira and @nickgrim are my fellow LLMs? :)

**Comment by terminalstatic** [comment]
@WGH- Well then I'd guess the already very low probability of the four of us ever having a beer together would drop sharply towards zero ;).

Tagged it.
